name: Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Set up R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # Install Dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Install IRKernel
      - name: Install IRKernel
        run: |
          Rscript -e 'install.packages("IRkernel")'
          Rscript -e 'IRkernel::installspec()'

      # Build the book
      - name: Build the book
        run: |
          jupyter-book build .

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
